name: ci

on:
  push:

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      id: build
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/ombi_sqlite_mysql:${{ github.ref_name }}
          ${{ secrets.DOCKERHUB_USERNAME }}/ombi_sqlite_mysql:latest
          ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/ombi_sqlite_mysql:${{ github.ref_name }}
          ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/ombi_sqlite_mysql:latest
        build_args: OMBI_VER=${{ github.ref_name }}
